### ISSUE TITLE
Error: "Currency amount must be non-negative number ..."

### ISSUE THREAD

**Issue by Forgev41** [paypal/rest-api-sample-app-php#18]
First, I like this sample much. It looks good and contains a real life situation.

Yet I get an error when running the sample.
What I did: I downloaded the project and imported it as a "Existing Maven Project". When I place an order I get the message:

Message:
Error code : 400 with response : {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].amount.total","issue":"Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by '.', optional thousands separator ',', limited to 7 digits before the decimal point"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"1d6d1f6c538ad"} 

I added some debugging code to AppHelper.java code to show the payment info.
I do not see why I get the message that the Currency amount must be non-negative number.
What I do see is that some values are stored with a comma and some with a point.
Living the the Netherlands default we write decimal values behind a comma instead of a point as in other parts of the world.
```
PayPal: Amount = {
  "currency": "USD",
  "total": "23,00",
  "details": {
    "shipping": "2",
    "subtotal": "20.00",
    "tax": "1"
  }
}
```
Total is written with comma and subtotal with point???

Stacktrace below:
```
OS: Windows 7,
Java: jdk1.8.0_31
Eclipse: Version: Luna Release (4.4.0) Build id: 20140612-0600

jun 05, 2015 10:16:33 AM org.apache.catalina.core.AprLifecycleListener init
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: C:\Program Files\Java\jdk1.8.0_31\jre\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Python27\;C:\Program Files\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Lua\5.1;C:\Program Files (x86)\Lua\5.1\clibs;C:\Program Files (x86)\Git\cmd;C:\Users\PCBoven\AppData\Roaming\Python\Scripts;C:\Program Files\Oracle\VirtualBox;.
jun 05, 2015 10:16:33 AM org.apache.tomcat.util.digester.SetPropertiesRule begin
WARNING: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.jee.server:rest-api-sample-app-java' did not find a matching property.
jun 05, 2015 10:16:33 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
jun 05, 2015 10:16:33 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
jun 05, 2015 10:16:33 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 424 ms
jun 05, 2015 10:16:33 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
jun 05, 2015 10:16:33 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.47
jun 05, 2015 10:16:34 AM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(D:\Eclipse\Java\.metadata\.plugins\org.eclipse.wst.server.core\tmp1\wtpwebapps\rest-api-sample-app-java\WEB-INF\lib\servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 2.3, section 9.7.2. Offending class: javax/servlet/Servlet.class
jun 05, 2015 10:16:34 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
jun 05, 2015 10:16:34 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
jun 05, 2015 10:16:34 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 763 ms
jun 05, 2015 10:17:32 AM com.paypal.core.LoggingManager log
SEVERE: object name already exists: PPUSERS in statement [CREATE TABLE ppusers (userid INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) not null,email VARCHAR(20),password VARCHAR(200),creditcard_id VARCHAR(40))]
PayPal: Amount = {
  "currency": "USD",
  "total": "23,00",
  "details": {
    "shipping": "2",
    "subtotal": "20.00",
    "tax": "1"
  }
}
PayPal: payment = {
  "intent": "sale",
  "payer": {
    "payment_method": "paypal"
  },
  "transactions": [
    {
      "amount": {
        "currency": "USD",
        "total": "23,00",
        "details": {
          "shipping": "2",
          "subtotal": "20.00",
          "tax": "1"
        }
      },
      "description": "Pizza0"
    }
  ],
  "redirect_urls": {
    "return_url": "http://localhost:8080/rest-api-sample-app-java/executepayment?orderId\u003d1",
    "cancel_url": "http://localhost:8080/rest-api-sample-app-java/cancelpayment?orderId\u003d1"
  }
}
jun 05, 2015 10:17:45 AM com.paypal.core.LoggingManager log
SEVERE: Error code : 400 with response : {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].amount.total","issue":"Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by '.', optional thousands separator ',', limited to 7 digits before the decimal point"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"75bcc7458812a"}
jun 05, 2015 10:17:45 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [pay] in context with path [/rest-api-sample-app-java] threw exception [com.paypal.core.rest.PayPalRESTException: Error code : 400 with response : {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].amount.total","issue":"Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by '.', optional thousands separator ',', limited to 7 digits before the decimal point"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"75bcc7458812a"}] with root cause
java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.sandbox.paypal.com/v1/payments/payment
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.paypal.core.HttpConnection.execute(HttpConnection.java:77)
	at com.paypal.core.rest.PayPalResource.execute(PayPalResource.java:321)
	at com.paypal.core.rest.PayPalResource.configureAndExecute(PayPalResource.java:245)
	at com.paypal.core.rest.PayPalResource.configureAndExecute(PayPalResource.java:191)
	at com.paypal.api.payments.Payment.create(Payment.java:293)
	at com.paypal.util.AppHelper.createPayment(AppHelper.java:160)
	at com.paypal.controller.PaymentServlet.handlePayment(PaymentServlet.java:180)
	at com.paypal.controller.PaymentServlet.doPost(PaymentServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Forgev41** [comment]
As said, the problem lies in the fact that in some countries the default locale write decimal values with a point instead of a point, for example in the Netherlands and Germany.
So String.format("%.2f", 23.0) will return the string "23,0" instead of "23.0".
See http://www.oracle.com/us/technologies/java/locale-140624.html

Try:
System.out.println("Default local:" + String.format(Locale.GERMAN,"%.2f", 23.0));
System.out.println("Default local:" + String.format(Locale.US, "%.2f", 23.0));

As a workaround I changed the original line in the AppHelper.java from
amount.setTotal(String.format("%.2f", total));
to
amount.setTotal(String.format(Locale.US, "%.2f", total));

**Comment by jaypatel512** [comment]
Also, it seems like you are in the wrong SDK Sample App. you might be looking one for Java which is located here: https://github.com/paypal/rest-api-sample-app-java

**Comment by Forgev41** [comment]
You are right, it was the Java version of this sample app.
